site_name: Make Classic Games
site_author: Make Classic Games
site_description: Canal de Twitch de creación de videojuegos clásicos. Aprende a crear juegos para consolas y ordenadores retro. https://twitch.tv/makeclassicgames
site_url: https://makeclassicgames.dev
nav:
  - Inicio: 'index.md'
  - Streams: 'stream.md'
  - Ejemplos: 'samples.md'
  - Libros: 'books.md'
  - Acerca de: 'about.md'
theme: 
  name: bootstrap386
extra_javascript:
  - 'js/noanim.js'
extra_css:
  - 'css/mobile.css'
copyright: (C) 2025 Make Classic Games - <a href="https://x.com/makeclassicgame" title="X"><img src="/img/xicon.png"/></a> <a href="https://bsky.app/profile/makeclassicgames.bsky.social" title="BlueSky"><img src="/img/bsky.jpeg"/></a> <a href="https://mastodon.social/@makeclassicgames" title="Mastodon" rel="me"><img src="/img/mastodon.png"/></a> <a href="https://github.com/makeclassicgames" title="Github"><img src="/img/github.png"/></a> <a href="https://discord.gg/P7984gThUq" title="Discord"><img src="/img/discord.png"/></a><a href="https://librecounter.org/referer/show" target="_blank" style="display:none;"><img src="https://librecounter.org/counter.svg" referrerPolicy="unsafe-url" /></a>
markdown_extensions:
  - attr_list